services:
  flask-app:
    build: 
      context: ./flask_app
      target: production
      args:
        PULSE_SERVER: /mnt/wslg/PulseServer
    ports:
      - "5000:5000"
    environment:
      - FASTAPI_URL=${FASTAPI_URL}
      - PULSE_SERVER=/mnt/wslg/PulseServer
    volumes:
      - ./flask_app:/home/appuser/flask_app
    tty: true
    depends_on:
      - fastapi-app
    networks:
      - app-network

  fastapi-app:
    build: 
      context: ./fastapi_app
      target: production
      args:
        SPEECH_KEY: ${SPEECH_KEY}
        SPEECH_REGION: ${SPEECH_REGION}
    env_file:
      - .env
    ports:
      - "8000:8000"
    environment:
      - SPEECH_KEY=${SPEECH_KEY}
      - SPEECH_REGION=${SPEECH_REGION}
    volumes:
      - ./fastapi_app:/home/appuser/fastapi_app
      # - /home/appuser/fastapi_app/vosk-model-ja-0.22
    tty: true
    networks:
      - app-network

networks:
  app-network:
    driver: bridge